.TH "TVKAISTA-DOWNLOAD" "1" "28 September 2009" "Debian Project" "Debian manual"
.SH "NAME"
tvkaista\-download \- batch download recordings from tvkaista.fi PVR service
.SH "SYNOPSIS"
.B fl\-record
.B [ options ]
.B test_case
.SH "DESCRIPTION"
TVkaista.fi is a PVR (personal video recorder) service with a www interface. This script allows registered tvkaista users to download the set of favorite recordings. See "tvkaista\-download --help" for options.
.SH "AUTHOR"
Tvkaista-download was written by Matti Pöllä.

